### ISSUE TITLE
When verifing from the mobile wallet, when the https://dev.uniresolver.io/ is down, the verification fails with gateway timeout

### ISSUE THREAD

**Issue by arheom** [Sphereon-Opensource/SSI-SDK#125]
From what I could see, the problem is that the OP has the code to receive a resolver as param and a failover to go to the uniresolver, but the OpSession never sends the resolver, using the requestOpts. The OpSession can be initialized to contain the IOPOptions, which contains the ResolveOpts, which contains the resolver, but when the getAuthorizationRequest() method is executed, resolver is not sent as a param here:

this.verifiedAuthorizationRequest = await op.verifyAuthorizationRequest(this.requestJwtOrUri), 

but at the OP.ts side, there is an optional param, which is taken into consideration, which can contain a resolver:
requestOpts?: { correlationId?: string; verification?: InternalVerification | ExternalVerification.

The mobile app also does not set the resolver, but it could to the session.

The result is a strong dependency to the https://dev.uniresolver.io and when it is down (and it is often), then the mobile wallet cannot respond to verifiers.

**Comment by arheom** [comment]
After some investigation, it seems the problem is both in the mobile wallet and in the OP.ts file.

Basically, in the mobile app, the agent needs to be initialized with the resolver object in the SIOPv2Provider.ts file, method siopRegisterSession, to include in the op property:
```
resolveOpts: {
        resolver: didResolver
      }
```
after importing the didResolver from the agent init file.

And in the OP.ts file, method: newVerifyAuthorizationRequestOpts the following line:
`verification: { ...this._verifyRequestOptions.verification, ...opts?.verification },`
overwrites whatever was set inside the this._verifyRequestOptions.verification by the agent with the opts?.verification which in the verifyAuthorizationRequest() case does not include the resolver. 

One fix here is to merge the verification object, so if the first param has the resolver, to not be overwritten by the second param.

**Comment by nklomp** [comment]
Hi @arheom Thanks for the great analysis. We have indeed fixed some SDK issues around this topic a while ago, which have not been included in the wallet yet.

 We have been really busy with some deadlines, so I have not been able yet to have a look at your findings. I do expect to be able to look at it roughly around this weekend.

**Comment by nklomp** [comment]
Again thanks for reporting and the great analysis.
There was an additional issue with well-known DIDs, where that library also didn't receive the agent resolver, thus always falling back to the universal resolver. Given the default is to verify well-known DIDs if there is a service end-point in the DID, we always check the DID, triggering a similar issue.

It is now fixed in the SDK and thus also in the wallets.
