### ISSUE TITLE
Get ERR_PACKAGE_PATH_NOT_EXPORTED when using ssi-sdk.oid4vci-issuer-rest-api.

### ISSUE THREAD

**Issue by t-kanuma** [Sphereon-Opensource/SSI-SDK#127]
Hi I'm a SSI developer in Japan. 
I've been trying to build OID4VCI Issuer using your SDK.
(As an aside, I'm using AFJ for building a OID4VCI wallet.)
Building typescript works, but when I start a node process, I get a following error. Is there a way to fix this?
My package.json is as follows. Thanks,

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/takahiro-kanuma/VSCodeProjects/sandbox/ssi-sandbox/sphereon-oid4vci/node_modules/did-jwt-vc/node_modules/uint8arrays/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
    at resolveExports (node:internal/modules/cjs/loader:554:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:594:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/takahiro-kanuma/VSCodeProjects/sandbox/ssi-sandbox/sphereon-oid4vci/node_modules/did-jwt-vc/node_modules/did-jwt/lib/index.cjs:1:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

```json
{
  "name": "oid4vci-trial",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "license": "MIT",
  "scripts": {
    "start": "tsc && node dist/index.js",
    "lint": "eslint ."
  },
  "dependencies": {
    "@sphereon/ssi-sdk-ext.did-provider-jwk": "0.14.0",
    "@sphereon/ssi-sdk-ext.key-manager": "0.14.0",
    "@sphereon/ssi-sdk.data-store": "^0.15.1",
    "@sphereon/ssi-sdk.oid4vci-issuer-rest-api": "^0.15.1",
    "@sphereon/ssi-sdk.vc-handler-ld-local": "^0.15.1",
    "@types/node": "^20.6.0",
    "@veramo/data-store": "4.2.0",
    "@veramo/did-manager": "4.2.0",
    "@veramo/did-resolver": "4.2.0",
    "did-resolver": "4.1.0",
    "log4js": "^6.9.1",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@tsconfig/node18": "^18.2.1",
    "@types/express": "^4.17.17",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "typescript": "^5.2.2"
  }
}
```

**Comment by t-kanuma** [comment]
I did `yarn resolution` to did-jwt-vc, and it's solved.

**Comment by nklomp** [comment]
Cool. Sorry for the late reply. Indeed you will need resolutions currently for did-jwt and did-jwt-vc, because they moved to ESM in a minor release. did-jwt-vc depends on did-jwt, which means that even if you provide an older version for did-jwt-vc you still might get in trouble. Then there was also an issue with a new Uint8arrays version: https://github.com/decentralized-identity/did-jwt-vc/issues/135

Glad you figured it out on your own 👍
