### ISSUE TITLE
Status List bitstring bit ordering

### ISSUE THREAD

**Issue by ejossev** [Sphereon-Opensource/SSI-SDK#138]
https://github.com/Sphereon-Opensource/SSI-SDK/blob/442bc7d37eb17429eb95afb8ba9a7709f4ca86e5/packages/vc-status-list/src/functions.ts#L170

Hi,

I believe that the underlying library interprets the bit ordering wrongly. 
Example:

```
> list = await sl.StatusList.decode({encodedList: 'H4sIAAAAAAAA_-3OMQEAAAgDIL_1b2Q0Y3gMErBTL98BAAAAAAAAAAAAAAAAAAAAOP19LQMAQAAA'})
StatusList {
  bitstring: Bitstring {
    bits: Uint8Array(16384) [
      192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0,
      ... 16284 more items
    ],
    length: 131072
  },
  length: 131072
}
> list.getStatus(1)
false
> list.getStatus(6)
true
```
The spec is quite clear that the left-most bit has index 0, the second left-most has index 1 etc. In my example, the two left-most bits are set to one, but the library sees as set indices 6 and 7.

**Comment by nklomp** [comment]
You are correct, it changed at one point in time.  hence why we have the other/old direction as only option in the lib. We will soon update everything and then move the default to the new direction.

**Comment by ejossev** [comment]
Thanks. Complementary question: how often does the wallet check if the credentials in it haven't been revoked?

**Comment by nklomp** [comment]
In current version we do not check in the background. We want to create some preferences from the user for it. We need some datastructures related to credentials to persist things like latest status checks etc , so we can combine it with prefs on when to check. We also need an interactive action to have the user check on demand.  It stands to reason that we would check once a week in the background for instance,  but also asynchronously check when a user opens a credential for the first time on a given day.

A verifier/relying party should of course always check on every interaction.
