### ISSUE TITLE
oid4vciIssueCredential() fails when verifying did:peer proof

### ISSUE THREAD

**Issue by void1042** [Sphereon-Opensource/SSI-SDK#140]
Hello again,

while trying to issue a credential, I noticed, that `oid4vciIssueCredential()` seems to fail when processing a request, that contains a proof of possession over a did:peer. Interestingly, this does not happen when the proof is over a did:key, even though my construction of the JWT is the same (using Veramo's [keyManagerSign()](https://veramo.io/docs/api/key-manager.keymanager.keymanagersign) ).

```
Error: invalid_signature: Signature invalid for JWT
    at verifyEd25519 (/home/void/Desktop/openidcomm/Code/node_modules/@sphereon/ssi-sdk.oid4vci-issuer/node_modules/did-jwt/src/VerifierAlgorithm.ts:179:22)
    at verifyJWSDecoded (/home/void/Desktop/openidcomm/Code/node_modules/@sphereon/ssi-sdk.oid4vci-issuer/node_modules/did-jwt/src/JWT.ts:337:38)
    at /home/void/Desktop/openidcomm/Code/node_modules/@sphereon/ssi-sdk.oid4vci-issuer/node_modules/did-jwt/src/JWT.ts:446:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

After some research I came across this [issue](https://github.com/decentralized-identity/did-jwt/issues/297) in the `did-jwt` library, which seems to describe the exact same issue I am facing. While it was fixed in version 7.4.0, this project seems to still use version 6.11.6 . I have written an example similar to the one in the issue, highlighting the difference between did:key and did:peer. Let me know if it is needed.

Am I doing something wrong or could this maybe really be the issue? Thanks a lot in advance

**Comment by nklomp** [comment]
Hi @void1042 You analysis is probably correct. Reason we are on this old version is because our SSI-SDK is compatible with Veramo 4.x only at the moment. V5.x moved to ESM, as do some of the deps it is using like did-jwt(-vc) which has a pretty significant impact on us as well. Having said that we will be moving to ESM soon, and thus we should be able to use latest versions again
