### ISSUE TITLE
Including dynamic token for endpoint protection

### ISSUE THREAD

**Issue by cre8** [Sphereon-Opensource/SSI-SDK#142]
The authentication option with a static token is good for demo purposes or for initialisation a veramo agent on demand for each call. But in my case I am using auth0 to add an access token that is valid for some minutes, longer than the user is interacting with the agent.

So extending the type like:
```
export interface IRestClientAuthenticationOpts {
    enabled?: boolean;
    staticBearerToken?: string;
    dynamicBearerToken?: () => Promise<string>;
}
```
And then update the OID4VCIRestClient like:
```
  private async createHeaders(existing?: Record<string, any>): Promise<HeadersInit> {
    const headers: HeadersInit = {
      ...existing,
      Accept: 'application/json',
    }
    if (this.authOpts?.enabled === true) {
      if (!this.authOpts.staticBearerToken || !this.authOpts.dynamicBearerToken) {
        throw Error(`Cannot have authentication enabled, whilst not enabling static bearer or a dynamic tokens at this point`)
      }
      if(this.authOpts.staticBearerToken && this.authOpts.dynamicBearerToken !== undefined) {
        throw Error(`Please either pass a static token or a dynamic token, not both.`);
      }
      if(this.authOpts.dynamicBearerToken !== undefined) {
        headers.Authorization = `Bearer ${await this.authOpts.dynamicBearerToken}`
      } else {
        headers.Authorization = `Bearer ${this.authOpts.staticBearerToken}`
      }
    }
    return headers
  }
  ```

To get more flexibility I think making `createHeaders` has to be async and the two calls in the class have to be updated

Should solve the problem. What do you think about the proposal?

**Comment by nklomp** [comment]
Yeah. IMO the best approach would be to just have a bearerToken property that is optional and accepts a string or a function returning a string. Then we can support both with just one property

**Comment by nklomp** [comment]
Is put on the backlog and highly likely to be picked up next sprint (starting next week)

**Comment by cre8** [comment]
@nklomp reopening it, since only the type of the arg was added, but not the usage of it, see: https://github.com/Sphereon-Opensource/SSI-SDK/blob/develop/packages/siopv2-oid4vp-rp-rest-client/src/agent/SIOPv2OID4VPRPRestClient.ts#L45
