### ISSUE TITLE
Get Issued Credentials

### ISSUE THREAD

**Issue by DevId1000** [Sphereon-Opensource/SSI-SDK#166]
Is there a way to somehow get all issued credentials by the agent?

**Comment by sanderPostma** [comment]
Are you referring to all the types of credentials it can issue, or all the credentials itself that have been issued? If it's the former, you can utilize the following endpoint configuration for that particular endpoint:

```
https://<agent host>/.well-known/openid-credential-issuer
```
Look under "credentials_supported".  An example can be found [here](https://[agent.banqup.demo.sphereon.com/.well-known/openid-credential-issuer](https://agent.banqup.demo.sphereon.com/.well-known/openid-credential-issuer)).

If it's the latter, I'll need to check this for you. We have a vc-status-list module, but I'll need to verify which credentials are stored there and what their life cycle is.

**Comment by DevId1000** [comment]
Yes, yes, i'm aware of this https://<agent host>/.well-known/openid-credential-issuer , but i'm asking about the second one  'all the credentials itself that have been issued'.

**Comment by nklomp** [comment]
Hi @DevId1000 By default the agent doesn't store issued credentials. We have the default Veramo datastore and datastoreOrm available though. There is also an optional parameter that can save the credential in the datastore during issuance. We probably aren't currently exposing that in the OID4VCI flows though.

```typescript
 const verifiableCredential = await agent.createVerifiableCredential({
        credential: {
          issuer: { id: identifiers[0].did },
          issuanceDate: new Date().toISOString(),
          credentialSubject: {
            id: 'did:web:community.veramo.io',
            you: 'Rock',
          },
        },
        save: true,
        proofFormat: 'jwt',
      })

```

Then, provided that you have configured the agent with a dataStore and dataStoreORM, you would be able to query the credential by hash/id, or query for multiple credentials even by claims in the credentials

See for instance the following methods
https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentials
https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentialsbyclaims

So something like this is entirely possible:

```typescript
  idOrHash = 'my VC id or calculated hash here';
 const uniqueVCs = await agent.dataStoreORMGetVerifiableCredentials({
      where: [
        {
          column: 'id',
          value: [idOrHash],
          op: 'Equal',
        },
      ],
    })
```

**Comment by DevId1000** [comment]
Thanks!

> Hi @DevId1000 By default the agent doesn't store issued credentials. We have the default Veramo datastore and datastoreOrm available though. There is also an optional parameter that can save the credential in the datastore during issuance. We probably aren't currently exposing that in the OID4VCI flows though.
> 
> ```ts
>  const verifiableCredential = await agent.createVerifiableCredential({
>         credential: {
>           issuer: { id: identifiers[0].did },
>           issuanceDate: new Date().toISOString(),
>           credentialSubject: {
>             id: 'did:web:community.veramo.io',
>             you: 'Rock',
>           },
>         },
>         save: true,
>         proofFormat: 'jwt',
>       })
> ```
> 
> Then, provided that you have configured the agent with a dataStore and dataStoreORM, you would be able to query the credential by hash/id, or query for multiple credentials even by claims in the credentials
> 
> See for instance the following methods https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentials https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentialsbyclaims
> 
> So something like this is entirely possible:
> 
> ```ts
>  const idOrHash = 'my VC id or calculated hash here';
>  const uniqueVCs = await agent.dataStoreORMGetVerifiableCredentials({
>       where: [
>         {
>           column: 'id',
>           value: [idOrHash],
>           op: 'Equal',
>         },
>       ],
>     })
> ```

Thanks!

**Comment by DevId1000** [comment]
> Hi @DevId1000 By default the agent doesn't store issued credentials. We have the default Veramo datastore and datastoreOrm available though. There is also an optional parameter that can save the credential in the datastore during issuance. We probably aren't currently exposing that in the OID4VCI flows though.
> 
> ```ts
>  const verifiableCredential = await agent.createVerifiableCredential({
>         credential: {
>           issuer: { id: identifiers[0].did },
>           issuanceDate: new Date().toISOString(),
>           credentialSubject: {
>             id: 'did:web:community.veramo.io',
>             you: 'Rock',
>           },
>         },
>         save: true,
>         proofFormat: 'jwt',
>       })
> ```
> 
> Then, provided that you have configured the agent with a dataStore and dataStoreORM, you would be able to query the credential by hash/id, or query for multiple credentials even by claims in the credentials
> 
> See for instance the following methods https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentials https://veramo.io/docs/api/data-store.datastoreorm.datastoreormgetverifiablecredentialsbyclaims
> 
> So something like this is entirely possible:
> 
> ```ts
>  const idOrHash = 'my VC id or calculated hash here';
>  const uniqueVCs = await agent.dataStoreORMGetVerifiableCredentials({
>       where: [
>         {
>           column: 'id',
>           value: [idOrHash],
>           op: 'Equal',
>         },
>       ],
>     })
> ```

Thanks!
