### ISSUE TITLE
Intermittent issue when verifying Authentication Request

### ISSUE THREAD

**Issue by niwim** [Sphereon-Opensource/ssi-sdk#50]
I'm getting an intermittent issue when trying to generate the AuthenticationRespons token using the did-auth-siop-op-authenticator package and `await agent.verifySiopAuthenticationRequestURI()` method

There is a 502 bad gateway thrown which makes little sense to me given that it should need to make any external request.

After some testing, I noticed that it worked if I let some time pass which makes it seem to be down to some async requests not waiting for the response.

Looking into the codebase I wonder if it might be down to the following line:
https://github.com/Sphereon-Opensource/ssi-sdk/blob/386efc71b18195004773fc74eb51b62cd3f5dd76/packages/did-auth-siop-op-authenticator/src/session/OpSession.ts#L133

There is no "await" running `verifyAuthenticationRequest() `which is async.

**Comment by nklomp** [comment]
closing this one as the respective module has seen many updates and is renamed in the mean time.
